### ISSUE TITLE
Change "private" checkbox with a flexible ACL system

### ISSUE THREAD

**Issue by Marvellanius** [ilestis/miscellany#17]
# Story
As a user, I want to have more control on the ACLs of my campaign.

List Members and Viewers, with several actions that can be allowed or disallowed.
Set a default ACL for a campaign.

# Work
1. Propose a new ACL system.
2. Implement the new ACL system.
3. Create a migration that will transform the old ACL into the new one.
4. Delete the old system.

# Tests
* TBD

**Comment by ilestis** [comment]
# General requirement
* As a creator, I wand to be able to set up custom roles and attribute my members to them. 
* Each role should should be able to have a default "permission" for each entity type that can be set.
* On each entity, I wand the current checkboxes to be replaces with a secondary tab for acl. On this new tab, I can assign a role or a member with a custom checkbox for each of the following: Read, Create, Edit, Delete.
* On each secondary entity (attribute, relation, quest location), I also want to be able to say what is visible or not.

# Challenges
* Making it easy for users who don't want to bother, but flexible enough for "power users".
* Queries will become a nightmare and slow if not done properly.
* Flexible so that Character's "goals" can still be hidden (or replace traits with attributes that can be customised).

**Comment by ilestis** [comment]
Still needs various UI improvements, awaiting feedback from users.
